# Generated by Django 6.0.3 on 2026-04-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_remove_lesson_course_remove_lesson_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Marque se a aula for gratuita para não-matriculados'),
        ),
    ]
