# Generated by Django 6.0.3 on 2026-04-12 19:44

import cursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_lesson_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=cursos.models.attachment_path),
        ),
        migrations.AlterField(
            model_name='blocovideo',
            name='video',
            field=models.FileField(max_length=500, upload_to=cursos.models.bloco_video_path),
        ),
    ]
