# Generated by Django 6.0.3 on 2026-05-17 01:06

import cursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_attachment_file_alter_blocovideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocovideo',
            name='subtitle',
            field=models.FileField(blank=True, help_text='Arquivo de legenda (.vtt)', max_length=500, null=True, upload_to=cursos.models.bloco_video_path),
        ),
    ]
