# Generated by Django 5.1.2 on 2026-05-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_blocovideo_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocovideo',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
